behaviors:
  CarBehaviour:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 5120
      learning_rate: 0.00035
      beta: 0.0025
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 264
      num_layers: 3

    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 0.99


    keep_checkpoints: 15
    checkpoint_interval: 1000000
    time_horizon: 264
    max_steps: 50000000
    summary_freq: 100000
    threaded: true

  CarBehaviourSAC:
    trainer_type: sac
    hyperparameters:
      batch_size: 128
      buffer_size: 50000
      learning_rate: 0.00035
      buffer_init_steps: 5000
      init_entcoef: 0.5
      steps_per_update: 1
      learning_rate_schedule: constant

    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 3

    reward_signals:
      extrinsic:
        gamma: 0.75
        strength: 0.99


    keep_checkpoints: 15
    time_horizon: 264
    max_steps: 30000000
    summary_freq: 20000
    threaded: false

  GridFoodCollector:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.00035
      learning_rate_schedule: constant
      batch_size: 128
      buffer_size: 50000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.5
      reward_signal_steps_per_update: 10.0

    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 3
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        gamma: 0.75
        strength: 0.99

    keep_checkpoints: 15
    time_horizon: 264
    max_steps: 30000000
    summary_freq: 20000
    threaded: false

